### ISSUE TITLE
Add support for zkSync and other chains

### ISSUE THREAD

**Issue by rareadam** [element-market/element-js-sdk#7]
I wanted to use the SDK to make a bulk listing of an ERC721 collection on zksync, but the SDK doesn't support this yet. I might be able to fork the SDK and add support by my own, but having at least some pointers from the team would be really helpful.

So please add support for this or give me some hints about which places would need to be updated. I hope it is only extending the Network enum and update the function which maps those networks to chain IDs.

**Comment by element-market** [comment]
https://github.com/element-market/element-js-sdk/commit/260e5ac9e6014ece92fec55330fef5c1ad653574

**Comment by rareadam** [comment]
Thank you!

element-market ***@***.***> schrieb am So., 24. Sept. 2023,
08:34:
